version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - 6379:6379
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Changed external port to 8000
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    command: >
      sh -c "npm run start"
    networks:
      - app_network

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app_network
    depends_on:
      - backend

networks:
  app_network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: